### ISSUE TITLE
$crud->addAction() method doesn't accept cyrillic symbols in return statement

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [atk4/atk4#624]
If you try to return cyrillic string from a model method you'll get something like this "\u044b\u043a\u043d\u043b \u0431\u0433\u043f\u044c\u0432\u0430\u044b\u0442\u0432\u043f \u044b\u043d\u0430\u044c\u044b"

**Comment by DarkSide666** [comment]
Problem is because of `json_encode` which by default doesn't respect cyrillic encoding.
Described here: http://stackoverflow.com/questions/410704/cyrillic-characters-in-phps-json-encode

In ATK 4.3.1 we set minimum required PHP version to PHP 5.4 and there is new constant `JSON_UNESCAPED_UNICODE` introduced. It looks that it should help in this situation.

**Comment by DarkSide666** [comment]
@KonstantinKolodnitsky can you please test this issue with JSON_UNESCAPED_UNICODE option added like this https://github.com/atk4/atk4/pull/682

**Comment by KonstantinKolodnitsky** [comment]
I don't use ATK4 anymore.

**Comment by alexeyostapets** [comment]
why? Probably you are the one who left the company and got paid totally, aren't you? :)

**Comment by DarkSide666** [comment]
Fixed: https://github.com/atk4/atk4/commit/25e028afd60354f50f19ec99852664c58b74d504

Test case:
```
$a = 'письмо отчаяния матери девушки';
var_dump(json_encode($a, JSON_UNESCAPED_UNICODE));
-------------
string(59) ""письмо отчаяния матери девушки""
```

**Comment by romaninsh** [comment]
This is open-source framework and no one is paid by anyone. We just want to make it better because it has potential.

**Comment by romaninsh** [comment]
As a note, addAction could have a better handling of a function method. For instance it could pop a dialog with View_Console inside it and output method execution details there. I am attaching sample:

![screen shot 2016-02-18 at 18 05 22](https://cloud.githubusercontent.com/assets/453929/13153091/361bd5ec-d66a-11e5-8223-f23b98b4f511.png)

**Comment by alexeyostapets** [comment]
Romans, could you read my message again attentively? Obviously I told about COMPANY's salary (I believe you know the name of the company, because I was working there for you, right?), not about framework's salary. And I wasn't paid by the company for 240 euro. More than one year... Good luck, businessmen....

**Comment by romaninsh** [comment]
The company in questions owes me about 50 times more than you, but it's not the place to discuss it.
